[package]
name = "chapter2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"
